[package]
name = "seed-datepicker"
version = "0.1.0"
authors = ["Tomas Miklovic <tommket@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seed = "0.8"
chrono = { version = "0.4", features = ["wasmbind"] }
num-traits = { version = "0.2", default-features = false }
derive_builder = "0.9"
derive-getters = "0.2"

[dev-dependencies]
proptest = "0.10"