name: Build Examples
on:
  push:
    branches: [master]

jobs:
  build-with-trunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-
      - name: Install trunk
        run: |
          cargo install trunk wasm-bindgen-cli
      - name: Build examples
        run: |
          output="$(pwd)/dist"
          for path in examples/*; do
            if [[ ! -d $path ]]; then
              continue
            fi
            example=$(basename "$path")
            # multi_thread doesn't work yet. See <https://github.com/thedodd/trunk/issues/40>.
            if [[ "$example" == "multi_thread" ]]; then
              continue
            fi
            echo "building: $example"
            (
              cd "$path"
              dist_dir="$output/$example"
              mkdir - p "$dist_dir"
              trunk build --release --dist "$dist_dir" --public-url "$PUBLIC_URL_PREFIX/$example"
            )
          done