name: Build Examples
on:
  push:
    branches: [master]

jobs:
  build-with-trunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-
      - name: Install trunk
        run: |
          cargo install trunk wasm-bindgen-cli
      - name: Build examples
        run: |
          for path in examples/*; do
            if [[ ! -d $path ]]; then
              continue
            fi
            example=$(basename "$path")
            echo "building: $example"
            (
              cd "$path"
              trunk build
            )
          done