name: Build Examples
on:
  push:
    paths-ignore:
    - '**.md'
    - '**.png'
    branches: [master]

  # also run it as a cron-job
  schedule:
    - cron: '0 2 * * 5' # At 02:00 on Friday

jobs:
  build-with-trunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-
      - name: Install trunk
        run: |
          cargo install trunk wasm-bindgen-cli
      - name: Build examples
        run: |
          ./.github/scripts/build_examples.sh
      - uses: jsmrcaga/action-netlify-deploy@v1.8.0
        if: ${{ github.event_name != 'schedule' }}
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: dist
          build_command: true