on: 
  push:
    paths-ignore:
    - '**.md'
    - '**.png'
  pull_request:
    paths-ignore:
    - '**.md'
    - '**.png'

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: test
      - name: Generate coverage file
        if: >
          github.ref == 'refs/heads/master'
        run: |
          cargo install cargo-tarpaulin --vers "^0.16"
          cargo tarpaulin --out Xml --verbose --ignore-tests
      - name: Upload to Codecov
        if: >
          github.ref == 'refs/heads/master'
        uses: codecov/codecov-action@v2.1.0
        with:
          file: cobertura.xml

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: clippy
          args: -- -D warnings